"""initial

Revision ID: a510d6626fd1
Revises: 
Create Date: 2026-03-17 00:28:49.390480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a510d6626fd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.Enum('individual', 'company', name='entity_type_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('badge_1', sa.Boolean(), nullable=False),
    sa.Column('badge_2', sa.Boolean(), nullable=False),
    sa.Column('badge_3', sa.Boolean(), nullable=False),
    sa.Column('badge_4', sa.Boolean(), nullable=False),
    sa.Column('is_publicly_searchable', sa.Boolean(), nullable=False),
    sa.Column('oauth_provider', sa.Enum('google', 'linkedin', name='oauth_provider_enum'), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('capability_declarations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('rag_capability', sa.Boolean(), nullable=False),
    sa.Column('rag_detail', sa.Text(), nullable=True),
    sa.Column('agent_systems', sa.Boolean(), nullable=False),
    sa.Column('agent_systems_detail', sa.Text(), nullable=True),
    sa.Column('tool_orchestration', sa.Boolean(), nullable=False),
    sa.Column('tool_orchestration_detail', sa.Text(), nullable=True),
    sa.Column('memory_systems', sa.Boolean(), nullable=False),
    sa.Column('memory_systems_detail', sa.Text(), nullable=True),
    sa.Column('deployment_type', sa.Enum('cloud', 'on_prem', 'hybrid', name='deployment_type_enum'), nullable=False),
    sa.Column('frameworks', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('proof_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.Enum('github_repo', 'live_demo', 'product_page', 'tech_blog', 'sandbox_deployment', 'case_study', name='artifact_type_enum'), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('validation_status', sa.Enum('pending', 'in_progress', 'passed', 'failed', name='validation_status_enum'), nullable=False),
    sa.Column('validation_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proof_artifacts_user_id'), 'proof_artifacts', ['user_id'], unique=False)
    op.create_table('capability_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('declaration_id', sa.Uuid(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('positioning', sa.Text(), nullable=True),
    sa.Column('focus_industries', sa.JSON(), nullable=False),
    sa.Column('verified_capabilities', sa.JSON(), nullable=False),
    sa.Column('declared_capabilities', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('Bronze', 'Silver', 'Gold', name='tier_enum'), nullable=False),
    sa.Column('execution_verified', sa.Boolean(), nullable=False),
    sa.Column('raw_llm_output', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['declaration_id'], ['capability_declarations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capability_documents')
    op.drop_index(op.f('ix_proof_artifacts_user_id'), table_name='proof_artifacts')
    op.drop_table('proof_artifacts')
    op.drop_table('capability_declarations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
